# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id_load', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=255)),
                ('orig_city', models.CharField(max_length=255)),
                ('orig_state', models.CharField(max_length=2)),
                ('orig_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('orig_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dest_city', models.CharField(max_length=255)),
                ('dest_state', models.CharField(max_length=2)),
                ('dest_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dest_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id_truck', models.IntegerField(primary_key=True, serialize=False)),
                ('truck', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
