# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('orig_city', models.CharField(max_length=255)),
                ('orig_state', models.CharField(max_length=2)),
                ('orig_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('orig_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dest_city', models.CharField(max_length=255)),
                ('dest_state', models.CharField(max_length=2)),
                ('dest_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dest_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
